modLoader = "javafml"
loaderVersion = "${mod_forge_loader_version}"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
authors = "${mod_author}"
description = '''
${mod_description}
'''
displayURL="${mod_website}"
logoFile = "assets/compact_storage/icon.png"

[[dependencies.compact_storage]]
modId = "neoforge"
type = "required"
versionRange = "${mod_forge_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.compact_storage]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"